services:
  kafka-kraft:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-kraft
    hostname: kafka-kraft
    ports:
      - "9092:9092"
      - "9101:9101" # JMX 모니터링 포트
    environment:
      # 노드 식별자
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-kraft:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'mhOYs7esSROR35QrnFq1eA'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka-kraft
    restart: on-failure
    environment:
      KAFKA_BROKER: 'kafka-kraft:29092'
      KAFKA_TOPIC: 'wikimedia.recentchange'